# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DZNEmptyDataSetTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DZNEmptyDataSetTest

  target 'DZNEmptyDataSetTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'AFNetworking'
pod 'PPNetworkHelper'
pod 'EasyNavigation','~>1.0'
end
